---
title: "Curriculum Vita"
output: word_document
layout: page
---

<a style="position: fixed; bottom:5px;left:25px; font-size:14px; font-weight:bold; color:#f7f7f7; padding:0 5px; border: solid thin #cc5500; border-radius: 10px; background-color: #cc5500;" href="#" title="Go to the top">Back to Top</a>

<link href="cv-print.css" type="text/css" rel="stylesheet">

<table style='width:100%; margin:0; font-size: 22px; float: top;'>
<tr><td align='left'>Maj Jason Freels</td><td align='right'><b>comm:</b> 937.255.3636 ext. 4676</td></tr>
<tr><td align='left'>Air Force Institute of Technology</td><td align="right"><b>DSN:</b> 785.3636 </td></tr>
<tr><td align="left">Dept. of Systems Engineering and Management</td><td align="right"><b>cell:</b> 937.430.6619</td></tr>
<tr><td align="left">2950 Hobson Way, Bldg. 640, Rm. 103</td><td align="right"><b>email:</b> <a href="mailto:jason.freels@afit.edu"><b>jason.freels@afit.edu</b></a></td></tr>
<tr><td align="left">WPAFB, OH 45433-7765</td><td align="right"> <b>url:</b>  <a target="_blank" href="http://auburngrads.github.io"><b>http://auburngrads.github.io</b></a></td></tr>
</table>

<br>

<font style="font-size:16pt !important; font-weight: bold;">
<center>
<small>
<a href="#academic">Academic Experience</a>&nbsp;&nbsp;&#9679;&nbsp;&nbsp;
<a href="#other">Other Experience</a>&nbsp;&nbsp;&#9679;&nbsp;&nbsp;
<a href="#publications">Publications</a>&nbsp;&nbsp;&#9679;&nbsp;&nbsp;<a href="#awards">Awards</a>
<br>
<a href="#proceedings">Proceedings & Presentations</a>&nbsp;&nbsp;&#9679;&nbsp;&nbsp;
<a href="#advising">Advising</a>&nbsp;&nbsp;&#9679;&nbsp;&nbsp;<a href="#certifications">Certifications</a>
</small>
</center>
</font>

<br>


<h1>Academic Experience<a name="academic"></a></h1>

<h2>Education</h2>

<font style="text-transform: uppercase;">
Doctor of Philosophy in Systems Engineering
</font>
__Air Force Institute of Technology__<span style="float:right;">***November 2013***</span>

- Areas of Concentration: System Reliability, Statistics
- __Dissertation:__ "Modeling Reliability Growth in Accelerated Stress Testing"

<font style="text-transform: uppercase;">
Masters of Science in Materials Science and Engineering
</font>
__Air Force Institute of Technology__<span style="float:right;">___September 2006___</span>

- Areas of Concentration: Structural Composite Materials
- __Thesis:__ "Modeling Fracture in Z-Pinned Composite Laminated using DYNA-3D"

<font style="text-transform: uppercase;">
Bacherlors of Science in Aerospace Engineering
</font>
__Auburn University__<span style="float:right;">___December 2000___</span>

<h2>Air Force Institute of Technology Record</h2>

<font style="text-transform: uppercase;">
Assistant Professor
</font>
__Department of Systems Engineering and Management__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Deputy Director
</font>
__Statistical Test and Analysis Techniques Center of Excellence__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Co-Primary Investigator
</font>
__Test Science Research Consortium__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Member - External Discovery Sub-Committee
</font>
__AFIT Quality Initiative Program__<span style="float:right;">___June 2016___</span>

<h2>Grants, Contracts, and Special Projects</h2>

<font style="text-transform: uppercase;">
Assistant Professor
</font>
__Department of Systems Engineering and Management__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Deputy Director
</font>
__Statistical Test and Analysis Techniques Center of Excellence__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Co-Primary Investigator
</font>
__Test Science Research Consortium__<span style="float:right;">___September 2013___</span>

<font style="text-transform: uppercase;">
Member - External Discovery Sub-Committee
</font>
__AFIT Quality Initiative Program__<span style="float:right;">___June 2016___</span>

# Other Experience <a name="other"></a>

## United States Air Force

<font style="text-transform: uppercase;">
F-16 Lead Structural Engineer
</font>
__Ogden Air Logistics Center - Hill AFB, UT__<span style="float:right;">___2001 - 2004___</span>

- Lead depot engineer supporting over 100 critical items used on 3,900 F-16's at 88 bases worldwide
- Responsible for the design and implementation of modifications and repair procedures to reduce maintenance costs, eliminate mission delays and enhance the performance capabilities of the F-16
- Lead F-16 engineer for Aircraft Battle Damage Repair (ABDR) mission; coordinates training activities, mentors trainees and evaluates battle damage repair procedures in ABDR exercises
- Personally designed depot repairs resulted in over 100 F-16 wings and major wing structures returned to service-saved more than $8M

<font style="text-transform: uppercase;">
Non-Destructive Evaluation Program Manager
</font>
__Air Force Research Laboratory - Wright-Patterson AFB, OH__<span style="float:right;">___2006 - 2007___</span>

- Directs R & D efforts and facilitates transition of novel non-destructive evaluation (NDE) technologies and techniques
- Develops broad research plan for inspection and characterization of new aircraft materials
- Lead engineer for three separate twelve-member teams charged with solving fleet-wide critical fracture issues at fuselage-wing attachment points for C-5, A-10, and KC-135 aircraft
- Initiated $1.5M KC-135 research program to baseline fleet fatigue damage.  Results of teardown evaluation enabled a five-year fleet life extension and $2M annual savings in maintenance costs

<font style="text-transform: uppercase;">
Military Assistant to the Director
</font>
__Air Force Research Laboratory - Wright-Patterson AFB, OH__<span style="float:right;">___2007 - 2008___</span>

- Oversees diverse processes for 1,200-person, $500M laboratory facilities to include four GSU's
- Prepares/directs briefings, visits, and lab tours for senior-level DOD, industry and foreign dignitaries
- Directed 1st AFRL Wargame Roadshow - Prioritized 150 research programs and $225M Science and technology budget for OSD Title 10 Wargame

<font style="text-transform: uppercase;">
Lead Materials Engineer
</font>
__Aeronautical Systems Center - Wright-Patterson AFB, OH__<span style="float:right;">___2008 - 2010___</span>

- Wing lead for modernization and technology transition efforts on over 500 mobility aircraft
- Provides expertise on sustainment requirements for over $44.5B in support systems acquisitions
- Lead materials engineer in Bagram AB C-17 crash recovery effort, efforts led to the successful completion of aircraft ferry flight to depot 74 days early - saved $220M jet from scrapping
- Led C-17 man-portable air defense system (MANPAD) survivability test program to reduce engine infrared signature by 75%.  Test results enabled a 42% increase in counter-measure effectiveness
- Led PACAF engine corrosion field evaluation.  Tested and qualified novel engine inlet coating material, resulted in the elimination a 168-hour overhaul

## Professional Development

- Air Command and Staff College, Air University, Maxwell AFB, AL
- Squadron Officer School, Air University, Maxwell AFB, AL
- Aerospace Basic Course, Air University, Maxwell AFB, AL
- Aircraft Battle Damage Repair, Technician Course, 649 CLSS, Hill AFB, UT
- Aircraft Battle Damage Repair, Assessor Course, 649 CLSS, Hill AFB, UT
- Aircraft Battle Damage Repair, Engineer Course, 649 CLSS, Hill AFB, UT
- Advanced Composites Engineering Course, USAF Advanced Composites Office, UT
- Air Force Materiel Command - Supply Chain Management Course, Air University, AL
- DAWIA Certifications - SPRDE (Level III); Program Management (Level II); Test and Evaluation (Level I)

# Professional Associations and Certifications <a name="certifications"></a>

- Member: American Society for Quality
- Member IEEE Reliability Society

# Publications <a name="publications"></a>

## Referreed Publications

- R. M. Vandawaker, D. R. Jacques, __J. K. Freels__ (2015)<br/>_"Impact of Prognostic Uncertainty in System Health Monitoring"_<br/>International Journal of Prognostics and Health Management: Vol 6 (Special Issue Uncertainty in PHM) 011 

- __J. K. Freels,__, J. J. Pignatiello, R. L. Warr,and R. R. Hill (2015)<br/>_"Bridging the Gap between Quantitative and Qualitative Accelerated Life Tests"_<br/>Quality and Reliability Engineering International, 31: 789–800. doi: 10.1002/qre.1636

- Collins D. H., __Freels J. K.__, Huzurbazar A. V., Warr R. L., and Weaver B. P. (2013)<br/> _"Accelerated Test Methods for Reliability Prediction"_<br/> Journal of Quality Technology, 45, No. 3, 244-259.

- Collins D. H., __Freels J. K.__, Huzurbazar A. V., Warr R. L., and Weaver B. P. (2012)<br/> _"Accelerated Test Methods for Reliability Prediction"_<br/> Los Alamos National Lab TSC Directorate Science Highlights, 134-135, LA-UR-12-20429.

## Preprints and Submitted Papers

- Vandawaker R. M., Jacques D. R., __Freels J. K.__, Ryan E., and Huscroft J. (2016)<br/> _"Health Monitoring Impact on Non-Repairable Component Supply Methods"_<br/> 
Journal of Quality in Maintenance Engineering

- __Freels J. K.__, Pignatiello J. J., Warr R. L., and Hill R. R. (2016)<br/>_"Maximum Likelihood Estimation for the Poly Weibull Distribution"_<br/> Quality Engineering

- __Freels J. K.__, Pignatiello J. J., Warr R. L., and Hill R. R. (2016)<br/>_"Simplified Modeling of the N-Fold Weibull Distribution"_<br/> Quality and Reliability Engineering International 

## Works In-Preparation (anticipated completion date)

<p style="text-transform: uppercase; font-size:115%; font-weight:bold; padding-top:10px;">
Referreed Journal Articles
</p>

- Deering P. R., __Freels J. K.__, and Valencia V. V. (2017)<br/> _Modeling Air Force civil infrastructure: A comparison of stochastic process models_<br/> ASCE-ASME Journal of Risk and Uncertainty in Engineering Systems, Part A: Civil Engineering.

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017)<br/> _SMRD: Statistical methods to accompany the text <u>Statistical Methods For Reliability Data</u>_<br/> The R Journal 

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017)<br/> _SMRD: Comprehensive life-data analysis in R</u>_<br/> Journal of Statistical Software 

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _teachingApps: A new package for building, and sharing shiny apps_<br/> The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _teachingApps: Easy A how-to manual for building, and sharing Shiny apps_<br/> The Journal of Statitics Education.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _AFIT: A R package of document templates for theses, dissertaions, and journal articles_<br/> The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _learningCurve: A R package of example code for building over 100 shiny apps_<br/> The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _evmR: A R package of example code for building over 100 shiny apps_<br/> The R Journal.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _publicLibs: A R package to find and manipulate data about U. S. Public Libraries_<br/> The R Journal.

<p style="text-transform: uppercase; font-size:115%; font-weight:bold;padding-top:10px;">
Books and Book Chapters
</p>

- Meeker W. Q., Escobar L. A. and __Freels J. K.__(2018)<br/> _Statistical Methods for Reliability Data, 2nd ed._<br/>John Wiley and Sons, Inc.

<p style="text-transform: uppercase; font-size:115%; font-weight:bold;padding-top:10px;">
Published Software
</p>

- __Freels J. K.__, Meeker W. Q., and Escobar L. A. (2017)<br/> _SMRD: Comprehensive analysis of reliability and survivability data_<br/> 
R package version 0.10.0.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _teachingApps: Example apps for teaching statistics, R programming, and shiny development_<br/> R package version 1.0.0.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _AFIT: Templates for AFIT theses, dissertations and various journal articles_<br/> R package version 1.0.0.

- __Freels J. K.__, DeGroot C., and Schultz D. (2017)<br/> _PublicLibs: Functions for manipulating and visualizing U. S. Public Library data_<br/> R package version 1.0.0.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _learningCurve: Templates for AFIT theses, dissertations and various journal articles_<br/> R package version 1.0.0.

- __Freels J. K.__ and Boehmke B. R. (2017)<br/> _evmR: A package of templates for AFIT theses and dissertations and various journal articles_<br/> R package version 1.0.0.

# Proceedings and Presentations<a name="proceedings"></a>

## Conference Proceedings

- Holm, E.S., Valencia, V.V., Thal, A.E., __Freels, J.K.__,Badiru, A.B. (2016)<br/>_Materials Testing and Cost Modeling for Composite Parts through Additive Manufacturing_<br/>Paper presented at the 13th Annual Acquisition Research Symposium, Monterrey, CA, May 2 – 4.

- Kilic H., Soni S. R., Patel R., and __Freels J. K.__ (2007)<br/>_Effect of Z-Fiber Percentage on the Fracture Behavior of DCB Specimens in Mode I_<br/>The 14th International Conference on Computational & Experimental Engineering and Sciences, Miami, FL, USA.

## Invited Presentations

## Short Courses

# Awards and Honors <a name="awards"></a>

- Lead engineer for Aeronautical System Center 2009 Team of the Year (Finalist)

- $10,000 <u>IDEA Award</u> for innovative repair design for F-16 belly door

- Lead engineer for AFMC's Supply Chain Management Team of the Year (2002)